import { Component, OnInit, ViewChild, inject } from '@angular/core';
import { FormControl, ReactiveFormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';
import { MatDialog, MatDialogModule } from '@angular/material/dialog';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatPaginator, MatPaginatorModule } from '@angular/material/paginator';
import { MatSelectModule } from '@angular/material/select';
import { MatSnackBar, MatSnackBarModule } from '@angular/material/snack-bar';
import { MatTableDataSource, MatTableModule } from '@angular/material/table';
import { UserAdmin } from '../../../models/user-admin.model';
import { UserAdminService } from '../../../services/user-admin.service';
import { ConfirmDialogComponent } from '../../../shared/components/confirm-dialog/confirm-dialog.component';
import { EmptyStateComponent } from '../../../shared/components/empty-state/empty-state.component';
import { ErrorMessageComponent } from '../../../shared/components/error-message/error-message.component';
import { LoadingSpinnerComponent } from '../../../shared/components/loading-spinner/loading-spinner.component';
import { ChangeRoleDialogComponent } from '../change-role-dialog/change-role-dialog.component';
import { ChangeStatusDialogComponent } from '../change-status-dialog.component';
import { CreateUserDialogComponent } from '../create-user-dialog.component';
@Component({selector:'app-user-list',standalone:true,imports:[ReactiveFormsModule,MatButtonModule,MatDialogModule,MatFormFieldModule,MatInputModule,MatPaginatorModule,MatSelectModule,MatSnackBarModule,MatTableModule,LoadingSpinnerComponent,EmptyStateComponent,ErrorMessageComponent],template:`<section class="page"><div class="header"><h1>Usuarios</h1><button mat-flat-button color="primary" (click)="create()">Crear usuario</button></div><div class="filters"><mat-form-field><mat-label>Buscar</mat-label><input matInput [formControl]="search" (input)="apply()"></mat-form-field><mat-form-field><mat-label>Rol</mat-label><mat-select [formControl]="role" (selectionChange)="apply()"><mat-option value="">Todos</mat-option><mat-option value="CLIENTE">CLIENTE</mat-option><mat-option value="ADMINISTRADOR">ADMINISTRADOR</mat-option><mat-option value="CAJERO">CAJERO</mat-option><mat-option value="ENCARGADO_SUCURSAL">ENCARGADO_SUCURSAL</mat-option></mat-select></mat-form-field><mat-form-field><mat-label>Estado</mat-label><mat-select [formControl]="status" (selectionChange)="apply()"><mat-option value="">Todos</mat-option><mat-option value="ACTIVO">ACTIVO</mat-option><mat-option value="INACTIVO">INACTIVO</mat-option></mat-select></mat-form-field></div>@if(loading){<app-loading-spinner/>}@else if(error){<app-error-message/>}@else if(!source.data.length){<app-empty-state message="No hay usuarios."/>}@else{<table mat-table [dataSource]="source"><ng-container matColumnDef="nombre"><th mat-header-cell *matHeaderCellDef>Nombre</th><td mat-cell *matCellDef="let u">{{u.nombres}} {{u.apellidos}}</td></ng-container><ng-container matColumnDef="correo"><th mat-header-cell *matHeaderCellDef>Correo</th><td mat-cell *matCellDef="let u">{{u.correo}}</td></ng-container><ng-container matColumnDef="rol"><th mat-header-cell *matHeaderCellDef>Rol</th><td mat-cell *matCellDef="let u">{{u.rol}}</td></ng-container><ng-container matColumnDef="estado"><th mat-header-cell *matHeaderCellDef>Estado</th><td mat-cell *matCellDef="let u">{{u.estado}}</td></ng-container><ng-container matColumnDef="acciones"><th mat-header-cell *matHeaderCellDef>Acciones</th><td mat-cell *matCellDef="let u"><button mat-button (click)="detail(u)">Detalle</button><button mat-button (click)="statusDialog(u)">{{u.estado==='ACTIVO'?'Desactivar':'Activar'}}</button><button mat-button (click)="roleDialog(u)">Rol</button></td></ng-container><tr mat-header-row *matHeaderRowDef="cols"></tr><tr mat-row *matRowDef="let row;columns:cols"></tr></table><mat-paginator [pageSize]="5" />}</section>`,styles:['.page{padding:2rem}.filters{display:flex;gap:1rem}table{width:100%}']})
export class UserListComponent implements OnInit {private service=inject(UserAdminService);private dialog=inject(MatDialog);private router=inject(Router);private snack=inject(MatSnackBar);@ViewChild(MatPaginator)paginator!:MatPaginator;source=new MatTableDataSource<UserAdmin>([]);search=new FormControl('');role=new FormControl('');status=new FormControl('');loading=true;error=false;cols=['nombre','correo','rol','estado','acciones'];ngOnInit(){this.load()}load(){this.loading=true;this.service.getUsers().subscribe({next:users=>{this.source.data=users;this.source.filterPredicate=(u,f)=>{const c=JSON.parse(f);return`${u.nombres} ${u.apellidos} ${u.correo}`.toLowerCase().includes(c.search)&&(!c.role||u.rol===c.role)&&(!c.status||u.estado===c.status)};this.apply();this.loading=false;setTimeout(()=>this.source.paginator=this.paginator)},error:()=>{this.error=true;this.loading=false}})}create(){this.dialog.open(CreateUserDialogComponent,{width:'32rem'}).afterClosed().subscribe(data=>{if(data)this.service.createUser(data).subscribe({next:()=>{this.load();this.snack.open('Usuario creado','Cerrar',{duration:3000})},error:(e:{error?:{message?:string}})=>this.snack.open(e.error?.message??'No fue posible crear el usuario','Cerrar',{duration:5000})})})}apply(){this.source.filter=JSON.stringify({search:(this.search.value??'').toLowerCase(),role:this.role.value??'',status:this.status.value??''})}detail(u:UserAdmin){void this.router.navigate(['/admin/users/detail',u.id_usuario])}statusDialog(u:UserAdmin){this.dialog.open(ChangeStatusDialogComponent,{data:u}).afterClosed().subscribe(r=>{if(!r)return;const action=()=>this.service.updateStatus(u.id_usuario,r).subscribe({next:x=>this.updateLocal(x),error:(e:{error?:{message?:string}})=>this.snack.open(e.error?.message??'No fue posible cambiar estado','Cerrar',{duration:5000})});if(r.estado==='INACTIVO')this.dialog.open(ConfirmDialogComponent,{data:{title:'Desactivar usuario',message:`Desactivar ${u.correo}?`}}).afterClosed().subscribe(ok=>{if(ok)action()});else action()})}roleDialog(u:UserAdmin){this.dialog.open(ChangeRoleDialogComponent,{data:u}).afterClosed().subscribe(r=>{if(r)this.service.updateRole(u.id_usuario,r).subscribe({next:x=>this.updateLocal(x),error:(e:{error?:{message?:string}})=>this.snack.open(e.error?.message??'No fue posible cambiar rol','Cerrar',{duration:5000})})})}private updateLocal(user:UserAdmin){this.source.data=this.source.data.map(u=>u.id_usuario===user.id_usuario?user:u);this.apply()} }
