import { Component, OnInit, ViewChild, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormControl, ReactiveFormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';
import { MatDialog, MatDialogModule } from '@angular/material/dialog';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatPaginator, MatPaginatorModule } from '@angular/material/paginator';
import { MatSelectModule } from '@angular/material/select';
import { MatSnackBar, MatSnackBarModule } from '@angular/material/snack-bar';
import { MatTableDataSource, MatTableModule } from '@angular/material/table';
import { OrderAdmin, OrderStatus } from '../../../models/order-admin.model';
import { OrderAdminService } from '../../../services/order-admin.service';
import { ConfirmDialogComponent } from '../../../shared/components/confirm-dialog/confirm-dialog.component';
import { EmptyStateComponent } from '../../../shared/components/empty-state/empty-state.component';
import { ErrorMessageComponent } from '../../../shared/components/error-message/error-message.component';
import { LoadingSpinnerComponent } from '../../../shared/components/loading-spinner/loading-spinner.component';
import { ChangeOrderStatusDialogComponent } from '../change-order-status-dialog.component';
@Component({selector:'app-order-list',standalone:true,imports:[CommonModule,ReactiveFormsModule,MatButtonModule,MatDialogModule,MatFormFieldModule,MatInputModule,MatPaginatorModule,MatSelectModule,MatSnackBarModule,MatTableModule,LoadingSpinnerComponent,EmptyStateComponent,ErrorMessageComponent],template:`<section class="page"><h1>Pedidos</h1><div class="filters"><mat-form-field><mat-label>Cliente</mat-label><input matInput [formControl]="search" (input)="apply()"></mat-form-field><mat-form-field><mat-label>Estado</mat-label><mat-select [formControl]="status" (selectionChange)="load()"><mat-option value="">Todos</mat-option><mat-option *ngFor="let s of states" [value]="s">{{s}}</mat-option></mat-select></mat-form-field></div>@if(loading){<app-loading-spinner/>}@else if(error){<app-error-message/>}@else if(!source.data.length){<app-empty-state message="No hay pedidos."/>}@else{<table mat-table [dataSource]="source"><ng-container matColumnDef="id"><th mat-header-cell *matHeaderCellDef>ID</th><td mat-cell *matCellDef="let o">#{{o.id_pedido}}</td></ng-container><ng-container matColumnDef="cliente"><th mat-header-cell *matHeaderCellDef>Cliente</th><td mat-cell *matCellDef="let o">{{o.cliente}}</td></ng-container><ng-container matColumnDef="fecha"><th mat-header-cell *matHeaderCellDef>Fecha</th><td mat-cell *matCellDef="let o">{{o.fecha}}</td></ng-container><ng-container matColumnDef="estado"><th mat-header-cell *matHeaderCellDef>Estado</th><td mat-cell *matCellDef="let o">{{o.estado}}</td></ng-container><ng-container matColumnDef="total"><th mat-header-cell *matHeaderCellDef>Total</th><td mat-cell *matCellDef="let o">{{o.total}}</td></ng-container><ng-container matColumnDef="acciones"><th mat-header-cell *matHeaderCellDef>Acciones</th><td mat-cell *matCellDef="let o"><button mat-button (click)="detail(o)">Ver detalle</button><button mat-button (click)="change(o)">Estado</button></td></ng-container><tr mat-header-row *matHeaderRowDef="cols"></tr><tr mat-row *matRowDef="let row;columns:cols"></tr></table><mat-paginator [pageSize]="5" />}</section>`,styles:['.page{padding:2rem}.filters{display:flex;gap:1rem}table{width:100%}']})
export class OrderListComponent implements OnInit {private service=inject(OrderAdminService);private dialog=inject(MatDialog);private router=inject(Router);private snack=inject(MatSnackBar);@ViewChild(MatPaginator)paginator!:MatPaginator;source=new MatTableDataSource<OrderAdmin>([]);search=new FormControl('');status=new FormControl('');loading=true;error=false;states:OrderStatus[]=['PENDIENTE','CONFIRMADO','PREPARANDO','ENVIADO','ENTREGADO','CANCELADO'];cols=['id','cliente','fecha','estado','total','acciones'];ngOnInit(){this.load()}load(){this.loading=true;this.service.getOrders({estado:this.status.value||undefined}).subscribe({next:o=>{this.source.data=o;this.source.filterPredicate=(x,f)=>x.cliente.toLowerCase().includes(f);this.apply();this.loading=false;setTimeout(()=>this.source.paginator=this.paginator)},error:()=>{this.error=true;this.loading=false}})}apply(){this.source.filter=(this.search.value??'').toLowerCase()}detail(o:OrderAdmin){void this.router.navigate(['/admin/orders/detail',o.id_pedido])}change(o:OrderAdmin){this.dialog.open(ChangeOrderStatusDialogComponent,{data:o,width:'28rem'}).afterClosed().subscribe((s:OrderStatus|undefined)=>{if(!s||s===o.estado)return;if(s==='CANCELADO'){this.dialog.open(ConfirmDialogComponent,{data:{title:'Cancelar pedido',message:`Cancelar pedido #${o.id_pedido}?`}}).afterClosed().subscribe(ok=>{if(ok)this.update(o,s)})}else this.update(o,s)})}private update(o:OrderAdmin,s:OrderStatus){this.service.updateStatus(o.id_pedido,{estado:s}).subscribe({next:r=>{this.source.data=this.source.data.map(x=>x.id_pedido===r.id_pedido?r:x);this.snack.open('Estado actualizado','Cerrar',{duration:3000})},error:(e:{error?:{message?:string}})=>this.snack.open(e.error?.message??'No fue posible actualizar','Cerrar',{duration:5000})})} }
