-- Extensión compatible para ventas presenciales, facturación y entrega.
ALTER TABLE pedido ALTER COLUMN id_cliente DROP NOT NULL;
ALTER TABLE pedido ADD COLUMN IF NOT EXISTS tipo_cliente VARCHAR(30) NOT NULL DEFAULT 'CLIENTE_REGISTRADO';
ALTER TABLE pedido ADD COLUMN IF NOT EXISTS tipo_venta VARCHAR(30) NOT NULL DEFAULT 'ONLINE';
ALTER TABLE pedido ADD COLUMN IF NOT EXISTS nit_ci VARCHAR(30);
ALTER TABLE pedido ADD COLUMN IF NOT EXISTS razon_social VARCHAR(150);
ALTER TABLE pedido ADD COLUMN IF NOT EXISTS tipo_entrega VARCHAR(30);
ALTER TABLE pedido ADD COLUMN IF NOT EXISTS id_sucursal_entrega INTEGER REFERENCES sucursal(id_sucursal);
ALTER TABLE pedido ADD COLUMN IF NOT EXISTS direccion_entrega VARCHAR(255);
ALTER TABLE pedido ADD COLUMN IF NOT EXISTS referencia_entrega VARCHAR(255);
ALTER TABLE pedido ADD COLUMN IF NOT EXISTS telefono_entrega VARCHAR(30);
