import { Component, inject } from '@angular/core';
import { NonNullableFormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { MatDialog, MatDialogModule } from '@angular/material/dialog';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatSnackBar, MatSnackBarModule } from '@angular/material/snack-bar';
import { MatTableModule } from '@angular/material/table';
import { AdminVariant } from '../../../models/variant-admin.model';
import { VariantAdminService } from '../../../services/variant-admin.service';
import { ConfirmDialogComponent } from '../../../shared/components/confirm-dialog/confirm-dialog.component';
import { EmptyStateComponent } from '../../../shared/components/empty-state/empty-state.component';
import { ErrorMessageComponent } from '../../../shared/components/error-message/error-message.component';
import { LoadingSpinnerComponent } from '../../../shared/components/loading-spinner/loading-spinner.component';
import { VariantFormComponent } from '../variant-form/variant-form.component';

@Component({selector:'app-variant-list',standalone:true,imports:[ReactiveFormsModule,MatButtonModule,MatDialogModule,MatFormFieldModule,MatInputModule,MatSnackBarModule,MatTableModule,LoadingSpinnerComponent,EmptyStateComponent,ErrorMessageComponent],template:`<section class="page"><div class="toolbar"><h1>Variantes</h1><button mat-flat-button color="primary" [disabled]="productForm.invalid" (click)="openForm()">Crear variante</button></div><form [formGroup]="productForm" (ngSubmit)="load()"><mat-form-field><mat-label>ID producto</mat-label><input matInput type="number" formControlName="productId"></mat-form-field><button mat-button>Consultar</button></form>@if(loading){<app-loading-spinner/>}@else if(error){<app-error-message/>}@else if(loaded&&!variants.length){<app-empty-state message="El producto no tiene variantes."/>}@else if(variants.length){<table mat-table [dataSource]="variants"><ng-container matColumnDef="sku"><th mat-header-cell *matHeaderCellDef>SKU</th><td mat-cell *matCellDef="let v">{{v.sku}}</td></ng-container><ng-container matColumnDef="talla"><th mat-header-cell *matHeaderCellDef>Talla</th><td mat-cell *matCellDef="let v">{{v.talla}}</td></ng-container><ng-container matColumnDef="color"><th mat-header-cell *matHeaderCellDef>Color</th><td mat-cell *matCellDef="let v">{{v.color}}</td></ng-container><ng-container matColumnDef="estado"><th mat-header-cell *matHeaderCellDef>Estado</th><td mat-cell *matCellDef="let v">{{v.estado}}</td></ng-container><ng-container matColumnDef="acciones"><th mat-header-cell *matHeaderCellDef>Acciones</th><td mat-cell *matCellDef="let v"><button mat-button (click)="openForm(v)">Editar</button><button mat-button color="warn" [disabled]="v.estado==='INACTIVO'" (click)="disable(v)">Desactivar</button></td></ng-container><tr mat-header-row *matHeaderRowDef="cols"></tr><tr mat-row *matRowDef="let row;columns:cols"></tr></table>}</section>`,styles:['.page{padding:2rem}.toolbar,form{display:flex;gap:1rem;align-items:center;margin-bottom:1rem}table{width:100%}']})
export class VariantListComponent { private fb=inject(NonNullableFormBuilder);private service=inject(VariantAdminService);private dialog=inject(MatDialog);private snack=inject(MatSnackBar);productForm=this.fb.group({productId:[0,[Validators.required,Validators.min(1)]]});variants:AdminVariant[]=[];loading=false;loaded=false;error=false;cols=['sku','talla','color','estado','acciones'];load(){if(this.productForm.invalid)return;this.loading=true;this.error=false;this.service.list(this.productForm.controls.productId.value).subscribe({next:v=>{this.variants=v;this.loaded=true;this.loading=false},error:()=>{this.error=true;this.loading=false}})}openForm(variant?:AdminVariant){if(this.productForm.invalid)return;this.dialog.open(VariantFormComponent,{data:{productId:this.productForm.controls.productId.value,variant},width:'30rem'}).afterClosed().subscribe(result=>{if(result){this.updateLocal(result);this.snack.open('Variante guardada','Cerrar',{duration:3000})}})}disable(variant:AdminVariant){this.dialog.open(ConfirmDialogComponent,{data:{title:'Desactivar variante',message:`Desactivar ${variant.sku}?`}}).afterClosed().subscribe(ok=>{if(ok)this.service.disable(variant.id_variante).subscribe({next:r=>{this.updateLocal(r);this.snack.open('Variante desactivada','Cerrar',{duration:3000})},error:()=>this.snack.open('No fue posible desactivar','Cerrar',{duration:5000})})})}private updateLocal(variant:AdminVariant){const i=this.variants.findIndex(v=>v.id_variante===variant.id_variante);this.variants=i<0?[...this.variants,variant]:this.variants.map(v=>v.id_variante===variant.id_variante?variant:v)} }
