import { Component, OnInit, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule, NonNullableFormBuilder } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatSelectModule } from '@angular/material/select';
import { MatTableModule } from '@angular/material/table';
import { AdminOrder, OrderStatus } from '../../models/order-admin.model';
import { OrderAdminService } from '../../services/order-admin.service';
@Component({selector:'app-order-management',standalone:true,imports:[CommonModule,ReactiveFormsModule,MatButtonModule,MatFormFieldModule,MatSelectModule,MatTableModule],template:`<section class="page"><h1>Pedidos</h1><mat-form-field><mat-label>Estado</mat-label><mat-select [formControl]="status"><mat-option value="">Todos</mat-option><mat-option *ngFor="let s of states" [value]="s">{{s}}</mat-option></mat-select></mat-form-field><button mat-button (click)="load()">Filtrar</button><table mat-table [dataSource]="items"><ng-container matColumnDef="cliente"><th mat-header-cell *matHeaderCellDef>Cliente</th><td mat-cell *matCellDef="let o">{{o.cliente}}</td></ng-container><ng-container matColumnDef="estado"><th mat-header-cell *matHeaderCellDef>Estado</th><td mat-cell *matCellDef="let o"><mat-select [value]="o.estado" (selectionChange)="change(o,$event.value)"><mat-option *ngFor="let s of states" [value]="s">{{s}}</mat-option></mat-select></td></ng-container><ng-container matColumnDef="total"><th mat-header-cell *matHeaderCellDef>Total</th><td mat-cell *matCellDef="let o">{{o.total}}</td></ng-container><tr mat-header-row *matHeaderRowDef="cols"></tr><tr mat-row *matRowDef="let row;columns:cols"></tr></table></section>`,styles:['.page{padding:2rem}table{width:100%}']})
export class OrderManagementComponent implements OnInit { private service=inject(OrderAdminService);private fb=inject(NonNullableFormBuilder);status=this.fb.control('');items:AdminOrder[]=[];states:OrderStatus[]=['PENDIENTE','CONFIRMADO','PREPARANDO','ENVIADO','ENTREGADO','CANCELADO'];cols=['cliente','estado','total'];ngOnInit(){this.load()}load(){this.service.list(this.status.value||undefined).subscribe(i=>this.items=i)}change(o:AdminOrder,s:OrderStatus){this.service.changeStatus(o.id_pedido,s).subscribe(()=>this.load())} }
