import { Component, OnInit, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { ApiService } from '../../core/services/api.service';
import { FittingThreeViewerComponent } from './components/fitting-three-viewer.component';
import { PreferredSizeResolver } from './services/preferred-size-resolver.service';

@Component({standalone:true,imports:[CommonModule,FormsModule,RouterLink,FittingThreeViewerComponent],styleUrl:'./experience.component.scss',template:`<main class="experience-page">
@if(mode==='recommendations') {<section class="recommendation-grid"><header class="experience-hero"><p class="eyebrow">CURADO PARA TI</p><h1>Recomendaciones</h1></header>@for(r of rows;track r.id_variante){<article><h2>{{r.nombre}}</h2><p>{{r.talla}} · {{r.color}} · Bs {{r.precio}}</p><p>{{r.motivo}}</p><a [routerLink]="['/catalog/product',r.id_producto]">Ver producto</a> <a [routerLink]="['/experience/fitting']" [queryParams]="{producto_id:r.id_producto,variante_id:r.id_variante,talla:r.talla,color:r.color}">Probar en vestidor</a><button (click)="add(r.id_variante)">Agregar</button></article>}</section><aside class="fashion-ai"><h2>FASHION AI</h2><p>{{assistantReply||'Consulta con reglas y productos reales.'}}</p><input [(ngModel)]="assistantQuery" (keyup.enter)="askAssistant()" placeholder="Quiero algo casual para una cena"><button (click)="askAssistant()" [disabled]="assistantLoading">{{assistantLoading?'Buscando…':'Enviar'}}</button>@if(assistantError){<p>{{assistantError}}</p>}@for(r of assistantRows;track r.id_variante){<article><strong>{{r.nombre}}</strong><p>{{r.talla}} · {{r.color}} · Bs {{r.precio}}</p><small>{{r.motivo}}</small><a [routerLink]="['/experience/fitting']" [queryParams]="{producto_id:r.id_producto,variante_id:r.id_variante,talla:r.talla,color:r.color}">Probar en vestidor</a></article>}</aside>}
@if(mode==='fitting'){<header class="fitting-hero"><h1>Vestidor virtual 3D</h1></header>@if(!bodyProfile&&!genericAvatar){<section class="security-card"><p>No tienes un perfil corporal configurado.</p><a routerLink="/profile/body">Crear mi perfil corporal</a><button (click)="genericAvatar=true">Continuar con avatar genérico</button></section>}<section class="fitting-layout"><app-fitting-three-viewer [garment]="selected" [accessory]="accessory" [bodyProfile]="bodyProfile"/><aside class="fitting-panel"><label>Prenda<select [(ngModel)]="variantId" (ngModelChange)="selectionChanged()"><option [ngValue]="0">Seleccionar prenda</option>@for(r of rows;track r.id_variante){<option [ngValue]="r.id_variante">{{r.nombre}} · {{r.talla}} · {{r.color}}</option>}</select></label><p>{{sizeWarning}}</p><button (click)="tryOn()" [disabled]="!variantId||busy">Probar en 3D</button>@if(selected){<p>{{selected.talla}} · {{selected.color}}</p><button (click)="add(selected.id_variante)">Agregar al carrito</button>}</aside></section><p class="fitting-note">Representación visual aproximada. No constituye una simulación física exacta del ajuste de la prenda.</p>}
</main>`})
export class ExperienceComponent implements OnInit {private api=inject(ApiService);private route=inject(ActivatedRoute);mode='';rows:any[]=[];selected:any=null;variantId=0;bodyProfile:any=null;preferences:any={};genericAvatar=false;accessory=false;busy=false;sizeWarning='';assistantQuery='';assistantReply='';assistantRows:any[]=[];assistantLoading=false;assistantError='';ngOnInit(){this.api.get('/api/body-profile').subscribe({next:p=>this.bodyProfile=p,error:()=>this.bodyProfile=null});this.api.get('/api/users/profile/preferences').subscribe({next:p=>this.preferences=p,error:()=>{}});this.route.data.subscribe(d=>{this.mode=d['mode'];this.load()});}load(){const path=this.mode==='recommendations'?'recommendations':'fitting';this.api.get<any[]>('/api/experience/'+path).subscribe({next:r=>{this.rows=r;if(this.mode==='fitting')this.applyInitialSelection()},error:e=>this.assistantError=e.error?.detail||'No fue posible cargar'});}private valid(v:any){return !!v&&v.estado!=='INACTIVO'&&v.stock_disponible!==0;}private applyInitialSelection(){const q=this.route.snapshot.queryParamMap;const product=Number(q.get('producto_id'));const requested=Number(q.get('variante_id'));const candidates=this.rows.filter(x=>!product||x.id_producto===product);let v=candidates.find(x=>x.id_variante===requested&&this.valid(x));if(!v){const size=q.get('talla'),color=q.get('color');v=candidates.find(x=>this.valid(x)&&(!size||x.talla===size)&&(!color||x.color===color));}if(!v&&candidates.length){const result=PreferredSizeResolver.resolve(candidates[0],this.preferences,candidates);v=result.variant;this.sizeWarning=result.warning||'';}if(!v&&!requested&&!q.get('talla'))v=candidates.find(x=>this.valid(x));if(v){this.variantId=v.id_variante;this.tryOn();}}selectionChanged(){this.selected=null;this.sizeWarning='';}tryOn(){const v=this.rows.find(x=>x.id_variante===this.variantId);if(!this.valid(v)){this.sizeWarning='La variante no está disponible actualmente.';return;}this.busy=true;this.api.post<any>('/api/experience/fitting',{id_variante:v.id_variante}).subscribe({next:x=>{this.selected={...v,...x};this.busy=false},error:()=>this.busy=false});}add(id:number){const v=this.rows.find(x=>x.id_variante===id);if(!this.valid(v)){this.sizeWarning='La variante no está disponible actualmente.';return;}this.api.post('/api/cart/items',{id_variante:id,cantidad:1}).subscribe();}askAssistant(){if(!this.assistantQuery.trim())return;this.assistantLoading=true;this.assistantError='';this.api.post<any>('/api/experience/fashion-assistant',{mensaje:this.assistantQuery}).subscribe({next:r=>{this.assistantRows=r.recomendaciones;this.assistantReply=r.respuesta;this.assistantLoading=false},error:e=>{this.assistantLoading=false;this.assistantError=e.error?.detail||'No fue posible consultar'}});}}
