import { Component, OnInit, inject } from '@angular/core';
import { MatButtonModule } from '@angular/material/button';
import { MatDialog, MatDialogModule } from '@angular/material/dialog';
import { MatTableModule } from '@angular/material/table';
import { AdminInventory } from '../../models/inventory-admin.model';
import { InventoryAdminService } from '../../services/inventory-admin.service';
import { LoadingSpinnerComponent } from '../../shared/components/loading-spinner/loading-spinner.component';
import { InventoryHistoryDialogComponent } from './inventory-history-dialog.component';
@Component({selector:'app-inventory-management',standalone:true,imports:[MatButtonModule,MatDialogModule,MatTableModule,LoadingSpinnerComponent],template:`<section class="page"><h1>Inventario</h1>@if(loading){<app-loading-spinner/>}@else{<table mat-table [dataSource]="items"><ng-container matColumnDef="producto"><th mat-header-cell *matHeaderCellDef>Producto</th><td mat-cell *matCellDef="let i">{{i.producto}}</td></ng-container><ng-container matColumnDef="sku"><th mat-header-cell *matHeaderCellDef>SKU</th><td mat-cell *matCellDef="let i">{{i.sku}}</td></ng-container><ng-container matColumnDef="sucursal"><th mat-header-cell *matHeaderCellDef>Sucursal</th><td mat-cell *matCellDef="let i">{{i.sucursal}}</td></ng-container><ng-container matColumnDef="stock"><th mat-header-cell *matHeaderCellDef>Stock</th><td mat-cell *matCellDef="let i">{{i.stock}}</td></ng-container><ng-container matColumnDef="acciones"><th mat-header-cell *matHeaderCellDef>Acciones</th><td mat-cell *matCellDef="let i"><button mat-button (click)="history(i)">Historial</button></td></ng-container><tr mat-header-row *matHeaderRowDef="cols"></tr><tr mat-row *matRowDef="let row;columns:cols"></tr></table>}</section>`,styles:['.page{padding:2rem}table{width:100%}']})
export class InventoryManagementComponent implements OnInit { private service=inject(InventoryAdminService);private dialog=inject(MatDialog);items:AdminInventory[]=[];loading=true;cols=['producto','sku','sucursal','stock','acciones'];ngOnInit(){this.service.list().subscribe({next:i=>{this.items=i;this.loading=false},error:()=>this.loading=false})}history(i:AdminInventory){this.dialog.open(InventoryHistoryDialogComponent,{data:{id:i.id_inventario},width:'48rem'})} }
