import { Component, Inject, inject } from '@angular/core';
import { NonNullableFormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { MAT_DIALOG_DATA, MatDialogModule, MatDialogRef } from '@angular/material/dialog';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { InventoryAdminService } from '../../services/inventory-admin.service';
@Component({selector:'app-stock-action-dialog',standalone:true,imports:[ReactiveFormsModule,MatButtonModule,MatDialogModule,MatFormFieldModule,MatInputModule],template:`<h2 mat-dialog-title>{{data.title}}</h2><form [formGroup]="form" (ngSubmit)="save()" mat-dialog-content><mat-form-field><mat-label>{{data.adjust?'Nuevo stock':'Cantidad'}}</mat-label><input matInput type="number" formControlName="cantidad"></mat-form-field><mat-form-field><mat-label>Motivo</mat-label><input matInput formControlName="motivo"></mat-form-field><div mat-dialog-actions align="end"><button mat-button mat-dialog-close type="button">Cancelar</button><button mat-flat-button color="primary" [disabled]="form.invalid">Guardar</button></div></form>`})
export class StockActionDialogComponent {private fb=inject(NonNullableFormBuilder);private service=inject(InventoryAdminService);private ref=inject(MatDialogRef<StockActionDialogComponent>);form=this.fb.group({cantidad:[0,[Validators.required,Validators.min(0)]],motivo:['',Validators.required]});constructor(@Inject(MAT_DIALOG_DATA) public data:{id:number;type:'increase'|'decrease'|'adjust';title:string;adjust?:boolean}){if(!data.adjust)this.form.controls.cantidad.addValidators(Validators.min(1))}save(){if(this.form.invalid)return;const v=this.form.getRawValue();const request=this.data.type==='increase'?this.service.increaseStock(this.data.id,{cantidad:v.cantidad,motivo:v.motivo}):this.data.type==='decrease'?this.service.decreaseStock(this.data.id,{cantidad:v.cantidad,motivo:v.motivo}):this.service.adjustStock(this.data.id,{nuevo_stock:v.cantidad,motivo:v.motivo});request.subscribe(i=>this.ref.close(i))} }
