import { Component, OnInit, inject } from '@angular/core';
import { NonNullableFormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { MatDialogModule, MatDialogRef } from '@angular/material/dialog';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatSelectModule } from '@angular/material/select';
import { MatSnackBar, MatSnackBarModule } from '@angular/material/snack-bar';
import { AdminBranch } from '../../../models/branch-admin.model';
import { AdminVariant } from '../../../models/variant-admin.model';
import { BranchAdminService } from '../../../services/branch-admin.service';
import { InventoryAdminService } from '../../../services/inventory-admin.service';
import { VariantAdminService } from '../../../services/variant-admin.service';

@Component({selector:'app-inventory-form',standalone:true,imports:[ReactiveFormsModule,MatButtonModule,MatDialogModule,MatFormFieldModule,MatInputModule,MatSelectModule,MatSnackBarModule],template:`<h2 mat-dialog-title>Registrar stock inicial</h2><form [formGroup]="form" (ngSubmit)="save()" mat-dialog-content><mat-form-field><mat-label>Sucursal</mat-label><mat-select formControlName="id_sucursal"><mat-option [value]="0">Seleccionar sucursal</mat-option>@for(branch of branches;track branch.id_sucursal){<mat-option [value]="branch.id_sucursal">{{branch.nombre}}</mat-option>}</mat-select></mat-form-field><mat-form-field><mat-label>Variante</mat-label><mat-select formControlName="id_variante"><mat-option [value]="0">Seleccionar variante</mat-option>@for(variant of variants;track variant.id_variante){<mat-option [value]="variant.id_variante">{{variant.producto}} - {{variant.color}} - {{variant.talla}}</mat-option>}</mat-select></mat-form-field><mat-form-field><mat-label>Cantidad inicial</mat-label><input matInput type="number" formControlName="stock"></mat-form-field><div mat-dialog-actions align="end"><button mat-button mat-dialog-close type="button">Cancelar</button><button mat-flat-button color="primary" [disabled]="form.invalid">Registrar stock</button></div></form>`})
export class InventoryFormComponent implements OnInit { private fb=inject(NonNullableFormBuilder);private service=inject(InventoryAdminService);private branchesService=inject(BranchAdminService);private variantsService=inject(VariantAdminService);private snack=inject(MatSnackBar);private ref=inject(MatDialogRef<InventoryFormComponent>);branches:AdminBranch[]=[];variants:AdminVariant[]=[];form=this.fb.group({id_variante:[0,[Validators.required,Validators.min(1)]],id_sucursal:[0,[Validators.required,Validators.min(1)]],stock:[0,[Validators.required,Validators.min(0)] ]});ngOnInit(){this.branchesService.list().subscribe({next:rows=>this.branches=rows.filter(row=>row.estado==='ACTIVA'),error:()=>this.snack.open('No fue posible cargar sucursales','Cerrar',{duration:4000})});this.variantsService.listAll().subscribe({next:rows=>this.variants=rows.filter(row=>row.estado==='ACTIVO'),error:()=>this.snack.open('No fue posible cargar variantes','Cerrar',{duration:4000})})}save(){if(this.form.invalid){this.form.markAllAsTouched();return}this.service.createInventory(this.form.getRawValue()).subscribe({next:i=>this.ref.close(i),error:(e:{error?:{message?:string}})=>this.snack.open(e.error?.message??'No fue posible registrar el stock','Cerrar',{duration:5000})})} }
